### ISSUE TITLE
remove Start() method

### ISSUE THREAD

**Issue by janfranchini** [gdgvda/cron#11]
`Cron` provides two similar methods: `Run()` and `Start()`.
https://github.com/gdgvda/cron/blob/5eb0ef714f0dea726f412d4d57328ba2011f50ae/cron.go#L214-L235

I think that calling `go cron.Run()` the behavior would be the same as `cron.Start()`. IMO we could remove `Start()` and keep just the `Run()` method, letting the user decide the execution goroutine on its own.

**Comment by rameshgkwd05** [comment]
I think they look similar, but they are not same as Start facilitates running cron scheduler in its own goroutine while Run()-> runs the cron scheduler in current goroutine.

**Comment by janfranchini** [comment]
Hi @rameshgkwd05,
I agree. What I'm proposing is a matter of API design. Assuming that calling `go cron.Run()` the behavior would be the same as using `cron.Start()`, IMHO exposing a single blocking method reduces the API surface and makes the usage more clear from a Go perspective. In order to run the cron scheduler in its own goroutine you would have to add the `go` keyword in front, as you would do for any other function. What do you think?

**Comment by janfranchini** [comment]
A use case I didn't consider is that of stopping the scheduler when using the first option I listed with blocking behavior. `select {}` blocks forever, instead I would expect the execution to resume in case the scheduler is stopped. For making this work with the first option we would need some communication mechanism so that externally it's possible to wait this event instead of waiting indefinitely.

Using the second solution this behavior would be for free. This point makes me lean towards the second option.

**Comment by janfranchini** [comment]
While trying to remove the `Start()` method I realized a side effect of using `go cron.Run()`.

https://github.com/gdgvda/cron/blob/abf1acdf6dbdec5d1b480ade880748b9006f2277/cron_test.go#L93-L112

Consider the change when starting the scheduler in the above test: without goroutine synchronization, the scheduler could start after the `Stop()` and/or `Add()` calls, resulting in unpredictable behavior. I don't think adding extra complexity to this makes sense, so I'm closing for now.
