### ISSUE TITLE
devcontainer setup

### ISSUE THREAD

**Issue by janfranchini** [gdgvda/cron#5]
A basic devcontainer setup would be useful in order to have a common environment to deal with.
Go 1.20 image with the installation of `golangci-lint` (https://golangci-lint.run/) should be enough as a first configuration.

**Comment by inalto** [comment]
Hello,
I have build one and written a small doc on how to use it.

**Comment by janfranchini** [comment]
Thank you @inalto, I've opened #7 with some refactor, feel free to review it.
