### ISSUE TITLE
new name?

### ISSUE THREAD

**Issue by Zavy86** [gdgvda/cron#6]
Hi, isn't cron name too generic?
How do you think about renaming to go-cron or cron-go or go-cron-management or whatever you like?

**Comment by janfranchini** [comment]
Since this is a fork I think that maintaining the original name is fine. It's short and pretty self-explaining IMO. @inalto what do you think?

**Comment by Zavy86** [comment]
Since it's abandoned I don't think they would be offended.. 
It might be appropriate for a better seo strategy :-P

**Comment by janfranchini** [comment]
There's a Go Blog post that could be relevant for this decision: https://go.dev/blog/package-names. It also mentions https://go.dev/doc/effective_go#names, another interesting resource. 

I still think that `cron` is a pretty good name for this package. Having to decide between SEO and code readability I would go for the latter. But of course, if we were able to find a nice trade off I would appreciate it.

**Comment by ryjogo** [comment]
go-schedule? :)

**Comment by janrnc** [comment]
I agree that the `scheduler` idea well describes the main feature. However I think there is some more valuable work to do, as for example in #20. Let's keep this for the future, thank you!
